[features]
seeds = false
[programs.localnet]
prestige_program = "DyiVPsExWgRDUk8dTNQB9bxirCC9e6C3cyhJN1MwQ7ac"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cp ./target/idl/prestige_program.json ./app/idl.json && yarn run ts-mocha -p ./tests/tsconfig.tests.json -t 1000000 tests/**/*.ts"
