[features]
seeds = false
[programs.devnet]
prestige_program = "J5yRbQdF4J37fGooLx6hc3tjJbRhQqU1R8MfobmGYT57"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cp ./target/idl/prestige_program.json ./app/idl.json && yarn run ts-mocha -p ./tests/tsconfig.tests.json -t 1000000 tests/**/*.ts"
